reference:
    class: File
    path: ../GRCh38_full_analysis_set_plus_decoy_hla.fa
bams:
    - {class: File, path: ../input_A.bam}
    - {class: File, path: ../input_Z.bam}
readgroups: ['@RG\tID:A\tSM:test-sample-1', '@RG\tID:Z\tSM:test-sample-1']
